name: test-arc-runner-set
on:
  workflow_dispatch:
  
jobs:
  job_1:
    runs-on: arc-runner-set


    steps:
      - name: Show NPU info
        run: |
          echo "hello world"
          sleep 3600
