name: repository_dispatch
on:
  workflow_dispatch:
jobs:
  job_1:
    runs-on: linux-arm64-npu-2
    container:
      image: m.daocloud.io/quay.io/ascend/vllm-ascend:v0.9.1-dev-openeuler

    steps:
      - name: Show NPU info
        run: |
          npu-smi info
