name: workflows_debug
on:
  workflow_dispatch:
jobs:
  job_1:
    runs-on: linux-arm64-npu-2
    container:
      image: swr.cn-southwest-2.myhuaweicloud.com/base_image/actions/actions-runner:latest

    steps:
      - name: Show NPU info
        run: |
          # npu-smi info
          sleep 20000

      - name: Checkout code
        uses: actions/checkout@v4
